apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: tech-test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /auth
            backend:
              serviceName: login-service
              servicePort: 80
          - path: /user
            backend:
              serviceName: login-service
              servicePort: 80
