apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: tech-test
  labels:
    app.service.io/name: user-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.deployment.io/name: user-deploy
