apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: tech-test
  labels:
    app.service.io/name: mongo-service
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
  selector:
    app.deployment.io/name: mongo-deploy
