apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: tech-test
  labels:
    app.deployment.io/name: mongo-deploy
spec:
  selector:
    matchLabels:
      app.deployment.io/name: mongo-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app.deployment.io/name: mongo-deploy
    spec:
      containers:
        - name: mongo-deploy
          image: mongo-auth
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: rootusername
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: rootpassword
          - name: MONGO_INITDB_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: dbusername
          - name: MONGO_INITDB_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: dbpassword
          - name: MONGO_INITDB_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: dbname
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pv-storage
              mountPath: /data/db
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvclaim
