apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: tech-test
  labels:
    app.deployment.io/name: mongo-deploy
spec:
  selector:
    matchLabels:
      app.deployment.io/name: mongo-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app.deployment.io/name: mongo-deploy
    spec:
      containers:
        - name: mongo-deploy
          image: mongo
          args: ["--dbpath", "/data/db"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_USER
              value: jay
            - name: MONGO_INITDB_PWD
              value: toor
            - name: MONGO_INITDB_DATABASE
              value: admin
          volumeMounts:
            - name: mongo-pv-storage
              mountPath: /data/db
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvclaim
